name: Publish New Release
on:
  pull_request: {}
  push:
    branches:
      - 'master'
    paths:
      - "action.yml"
      - "version.txt"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Tag Release (Dry-run)
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: npx semantic-release --dry-run

      - name: Tag Release
        if: ${{ github.ref == 'refs/heads/master' }}
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: npx semantic-release
